name: fitness_x
description: "A fitness interview app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked_hooks: ^0.2.3
  stacked: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - asset/homepage/
    - asset/bottom_icons/
    - asset/homepage/best/
    - asset/homepage/challenge/
    - asset/homepage/warm_up/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato/Lato-Regular.ttf
        - asset: fonts/lato/Lato-Italic.ttf
          style: italic